// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: proto/data_agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_data_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_data_agent_proto_rawDescGZIP(), []int{0}
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformVer   string                 `protobuf:"bytes,5,opt,name=platform_ver,json=platformVer,proto3" json:"platform_ver,omitempty"`
	KernelVer     string                 `protobuf:"bytes,6,opt,name=kernel_ver,json=kernelVer,proto3" json:"kernel_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_proto_data_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_proto_data_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Host) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Host) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Host) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Host) GetPlatformVer() string {
	if x != nil {
		return x.PlatformVer
	}
	return ""
}

func (x *Host) GetKernelVer() string {
	if x != nil {
		return x.KernelVer
	}
	return ""
}

type HostList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*Host                `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostList) Reset() {
	*x = HostList{}
	mi := &file_proto_data_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostList) ProtoMessage() {}

func (x *HostList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostList.ProtoReflect.Descriptor instead.
func (*HostList) Descriptor() ([]byte, []int) {
	return file_proto_data_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HostList) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type DiskMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,4,opt,name=free,proto3" json:"free,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,5,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetric) Reset() {
	*x = DiskMetric{}
	mi := &file_proto_data_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetric) ProtoMessage() {}

func (x *DiskMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetric.ProtoReflect.Descriptor instead.
func (*DiskMetric) Descriptor() ([]byte, []int) {
	return file_proto_data_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DiskMetric) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskMetric) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskMetric) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *DiskMetric) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *DiskMetric) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

type NetMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	PacketsSent   uint64                 `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsRecv   uint64                 `protobuf:"varint,5,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"`
	ErrIn         uint64                 `protobuf:"varint,6,opt,name=err_in,json=errIn,proto3" json:"err_in,omitempty"`
	ErrOut        uint64                 `protobuf:"varint,7,opt,name=err_out,json=errOut,proto3" json:"err_out,omitempty"`
	DropIn        uint64                 `protobuf:"varint,8,opt,name=drop_in,json=dropIn,proto3" json:"drop_in,omitempty"`
	DropOut       uint64                 `protobuf:"varint,9,opt,name=drop_out,json=dropOut,proto3" json:"drop_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetMetric) Reset() {
	*x = NetMetric{}
	mi := &file_proto_data_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetMetric) ProtoMessage() {}

func (x *NetMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetMetric.ProtoReflect.Descriptor instead.
func (*NetMetric) Descriptor() ([]byte, []int) {
	return file_proto_data_agent_proto_rawDescGZIP(), []int{4}
}

func (x *NetMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetMetric) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetMetric) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *NetMetric) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *NetMetric) GetPacketsRecv() uint64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

func (x *NetMetric) GetErrIn() uint64 {
	if x != nil {
		return x.ErrIn
	}
	return 0
}

func (x *NetMetric) GetErrOut() uint64 {
	if x != nil {
		return x.ErrOut
	}
	return 0
}

func (x *NetMetric) GetDropIn() uint64 {
	if x != nil {
		return x.DropIn
	}
	return 0
}

func (x *NetMetric) GetDropOut() uint64 {
	if x != nil {
		return x.DropOut
	}
	return 0
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HostId        int64                  `protobuf:"varint,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Uptime        uint64                 `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Cpu           float64                `protobuf:"fixed64,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram           float64                `protobuf:"fixed64,5,opt,name=ram,proto3" json:"ram,omitempty"`
	Disk          []*DiskMetric          `protobuf:"bytes,6,rep,name=disk,proto3" json:"disk,omitempty"`
	Network       []*NetMetric           `protobuf:"bytes,7,rep,name=network,proto3" json:"network,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_data_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_data_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Metric) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Metric) GetHostId() int64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *Metric) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Metric) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Metric) GetRam() float64 {
	if x != nil {
		return x.Ram
	}
	return 0
}

func (x *Metric) GetDisk() []*DiskMetric {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *Metric) GetNetwork() []*NetMetric {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Metric) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type MetricList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricList) Reset() {
	*x = MetricList{}
	mi := &file_proto_data_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricList) ProtoMessage() {}

func (x *MetricList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricList.ProtoReflect.Descriptor instead.
func (*MetricList) Descriptor() ([]byte, []int) {
	return file_proto_data_agent_proto_rawDescGZIP(), []int{6}
}

func (x *MetricList) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HostName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostName) Reset() {
	*x = HostName{}
	mi := &file_proto_data_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostName) ProtoMessage() {}

func (x *HostName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostName.ProtoReflect.Descriptor instead.
func (*HostName) Descriptor() ([]byte, []int) {
	return file_proto_data_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HostName) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_proto_data_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_agent_proto_rawDescGZIP(), []int{8}
}

func (x *MetricRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MetricRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_data_agent_proto protoreflect.FileDescriptor

const file_proto_data_agent_proto_rawDesc = "" +
	"\n" +
	"\x16proto/data_agent.proto\x12\n" +
	"data_agent\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xa0\x01\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12!\n" +
	"\fplatform_ver\x18\x05 \x01(\tR\vplatformVer\x12\x1d\n" +
	"\n" +
	"kernel_ver\x18\x06 \x01(\tR\tkernelVer\"2\n" +
	"\bHostList\x12&\n" +
	"\x05hosts\x18\x01 \x03(\v2\x10.data_agent.HostR\x05hosts\"\x81\x01\n" +
	"\n" +
	"DiskMetric\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x04 \x01(\x04R\x04free\x12!\n" +
	"\fused_percent\x18\x05 \x01(\x01R\vusedPercent\"\x87\x02\n" +
	"\tNetMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x03 \x01(\x04R\tbytesRecv\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x04R\vpacketsSent\x12!\n" +
	"\fpackets_recv\x18\x05 \x01(\x04R\vpacketsRecv\x12\x15\n" +
	"\x06err_in\x18\x06 \x01(\x04R\x05errIn\x12\x17\n" +
	"\aerr_out\x18\a \x01(\x04R\x06errOut\x12\x17\n" +
	"\adrop_in\x18\b \x01(\x04R\x06dropIn\x12\x19\n" +
	"\bdrop_out\x18\t \x01(\x04R\adropOut\"\xfa\x01\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\x03R\x06hostId\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x04R\x06uptime\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03ram\x18\x05 \x01(\x01R\x03ram\x12*\n" +
	"\x04disk\x18\x06 \x03(\v2\x16.data_agent.DiskMetricR\x04disk\x12/\n" +
	"\anetwork\x18\a \x03(\v2\x15.data_agent.NetMetricR\anetwork\x12.\n" +
	"\x04time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04time\":\n" +
	"\n" +
	"MetricList\x12,\n" +
	"\ametrics\x18\x01 \x03(\v2\x12.data_agent.MetricR\ametrics\"&\n" +
	"\bHostName\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"A\n" +
	"\rMetricRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit2v\n" +
	"\vHostService\x124\n" +
	"\tListHosts\x12\x11.data_agent.Empty\x1a\x14.data_agent.HostList\x121\n" +
	"\aGetHost\x12\x14.data_agent.HostName\x1a\x10.data_agent.Host2\x90\x01\n" +
	"\rMetricService\x12@\n" +
	"\vListMetrics\x12\x19.data_agent.MetricRequest\x1a\x16.data_agent.MetricList\x12=\n" +
	"\x10GetLatestMetrics\x12\x11.data_agent.Empty\x1a\x16.data_agent.MetricListB\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_data_agent_proto_rawDescOnce sync.Once
	file_proto_data_agent_proto_rawDescData []byte
)

func file_proto_data_agent_proto_rawDescGZIP() []byte {
	file_proto_data_agent_proto_rawDescOnce.Do(func() {
		file_proto_data_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_agent_proto_rawDesc), len(file_proto_data_agent_proto_rawDesc)))
	})
	return file_proto_data_agent_proto_rawDescData
}

var file_proto_data_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_data_agent_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: data_agent.Empty
	(*Host)(nil),                  // 1: data_agent.Host
	(*HostList)(nil),              // 2: data_agent.HostList
	(*DiskMetric)(nil),            // 3: data_agent.DiskMetric
	(*NetMetric)(nil),             // 4: data_agent.NetMetric
	(*Metric)(nil),                // 5: data_agent.Metric
	(*MetricList)(nil),            // 6: data_agent.MetricList
	(*HostName)(nil),              // 7: data_agent.HostName
	(*MetricRequest)(nil),         // 8: data_agent.MetricRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_data_agent_proto_depIdxs = []int32{
	1, // 0: data_agent.HostList.hosts:type_name -> data_agent.Host
	3, // 1: data_agent.Metric.disk:type_name -> data_agent.DiskMetric
	4, // 2: data_agent.Metric.network:type_name -> data_agent.NetMetric
	9, // 3: data_agent.Metric.time:type_name -> google.protobuf.Timestamp
	5, // 4: data_agent.MetricList.metrics:type_name -> data_agent.Metric
	0, // 5: data_agent.HostService.ListHosts:input_type -> data_agent.Empty
	7, // 6: data_agent.HostService.GetHost:input_type -> data_agent.HostName
	8, // 7: data_agent.MetricService.ListMetrics:input_type -> data_agent.MetricRequest
	0, // 8: data_agent.MetricService.GetLatestMetrics:input_type -> data_agent.Empty
	2, // 9: data_agent.HostService.ListHosts:output_type -> data_agent.HostList
	1, // 10: data_agent.HostService.GetHost:output_type -> data_agent.Host
	6, // 11: data_agent.MetricService.ListMetrics:output_type -> data_agent.MetricList
	6, // 12: data_agent.MetricService.GetLatestMetrics:output_type -> data_agent.MetricList
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_data_agent_proto_init() }
func file_proto_data_agent_proto_init() {
	if File_proto_data_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_agent_proto_rawDesc), len(file_proto_data_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_data_agent_proto_goTypes,
		DependencyIndexes: file_proto_data_agent_proto_depIdxs,
		MessageInfos:      file_proto_data_agent_proto_msgTypes,
	}.Build()
	File_proto_data_agent_proto = out.File
	file_proto_data_agent_proto_goTypes = nil
	file_proto_data_agent_proto_depIdxs = nil
}
